server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /api

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_USER_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: MyHikariCP
  jpa:
    hibernate:
      ddl-auto: update
      format-sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      client:
        registration:        # <-- Khai báo thông tin "đăng ký client" với Google
          google:
            client-id: ${OAUTH_CLIENT_ID}           # <-- Mã định danh của client (lấy từ Google Cloud Console)
            client-secret: ${OAUTH_CLIENT_SECRET}   # <-- Mã bí mật (secret key) của client
            scope:                                  # <-- Quyền truy cập yêu cầu
              - openid
              - profile
              - email
            # {baseUrl} - Spring Security sẽ tự động thay bằng URL gốc (origin) của ứng dụng
            redirect-uri: "{baseUrl}/api/auth/oauth2/callback/flowName=GeneralOAuthFlow"   # URI mà Google sẽ chuyển hướng tới sau khi người dùng đăng nhập thành công
        provider:           # <-- Thông tin của nhà cung cấp OAuth (Google)
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth  # <-- URL người dùng sẽ được chuyển tới để đăng nhập
            token-uri: https://www.googleapis.com/oauth2/v4/token         # <-- URL để đổi code lấy access token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo # <-- URL lấy thông tin người dùng
            user-name-attribute: sub  # <-- Thuộc tính duy nhất trong user info để định danh người dùng (sub = subject ID)
  mail:
    from: ${SMTP_FROM}
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_MAIL}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  websocket:
    sockjs:
      enabled: true
      client-library-url: https://cdn.jsdelivr.net/npm/sockjs-client@1/dist/sockjs.min.js

aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}
  s3:
    bucketName: ${AWS_S3_BUCKET}
    bucketUrl: ${AWS_S3_BUCKET_URL}

stripe:
  secret:
    key: ${STRIPE_SECRET_KEY}
  webhook:
    secret: ${STRIPE_WEBHOOK_KEY}

frontend:
  url: ${FRONTEND_URL}

jwt:
  secret: myVerySecretKeyThatIsAtLeast256BitsLongForHS256Algorithm
  expiration: 86400

app:
  refresh-token:
      secret-key: 9K7mP2nQ8vR4xW6zA3bE5gH1jL9mP2nQ
      expiration: 604800
  priceInfo:
    service-fee: 29
    tax-rate: 0.1
  chat:
    max-message-length: 1000
    max-file-size: 10MB
    allowed-file-types: image/jpeg,image/png,image/gif,application/pdf,text/plain

