server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /api

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_USER_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: MyHikariCP
  jpa:
    hibernate:
      ddl-auto: update
      format-sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_CLIENT_ID}
            client-secret: ${OAUTH_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/api/auth/oauth2/callback/"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  mail:
    from: ${SMTP_FROM}
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_MAIL}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}
  s3:
    bucketName: ${AWS_S3_BUCKET}

frontend:
  url: ${FRONTEND_URL}

jwt:
  secret: myVerySecretKeyThatIsAtLeast256BitsLongForHS256Algorithm
  expiration: 86400

app:
  refresh-token:
      secret-key: 9K7mP2nQ8vR4xW6zA3bE5gH1jL9mP2nQ
      expiration: 604800
  priceInfo:
    service-fee: 29
    taxes: 0.1

